#Task2: Try Linear regression on same prediction data using Tensorflow

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [3]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
print("targets :\n",targets)

targets :
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>


In [4]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)

print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.67294566, 0.61793358],
       [0.29639916, 0.2219502 ],
       [0.27813792, 0.60590377]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-1.69496834,  0.91383536])>


In [5]:
def model(s):
    return s @ v + r

In [6]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 79.24873866  86.9475117 ]
 [103.42703904 115.45524934]
 [112.70079004 119.55780148]
 [ 89.98175561  95.90535813]
 [ 92.66225523 107.2717348 ]
 [ 79.24873866  86.9475117 ]
 [103.42703904 115.45524934]
 [112.70079004 119.55780148]
 [ 89.98175561  95.90535813]
 [ 92.66225523 107.2717348 ]
 [ 79.24873866  86.9475117 ]
 [103.42703904 115.45524934]
 [112.70079004 119.55780148]
 [ 89.98175561  95.90535813]
 [ 92.66225523 107.2717348 ]], shape=(15, 2), dtype=float64)


In [7]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(1009.5802546854889, shape=(), dtype=float64)


In [8]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1009.5802546854889
 
 Epoch count: 1 
 Loss value: 844.5790257682025
 
 Epoch count: 2 
 Loss value: 715.6746539829497
 
 Epoch count: 3 
 Loss value: 612.4945530868811
 
 Epoch count: 4 
 Loss value: 528.1643805100047
 
 Epoch count: 5 
 Loss value: 458.04554020266573
 
 Epoch count: 6 
 Loss value: 398.9395724845501
 
 Epoch count: 7 
 Loss value: 348.58533761295195
 
 Epoch count: 8 
 Loss value: 305.33999378726674
 
 Epoch count: 9 
 Loss value: 267.97550355042665
 
 Epoch count: 10 
 Loss value: 235.5478944886084
 
 Epoch count: 11 
 Loss value: 207.3124560216985
 
 Epoch count: 12 
 Loss value: 182.6680432437348
 
 Epoch count: 13 
 Loss value: 161.11991429417915
 
 Epoch count: 14 
 Loss value: 142.25444673153658
 
 Epoch count: 15 
 Loss value: 125.72153496493651
 
 Epoch count: 16 
 Loss value: 111.22201190920023
 
 Epoch count: 17 
 Loss value: 98.49840589675021
 
 Epoch count: 18 
 Loss value: 87.32795266892441
 
 Epoch count: 19 
 Loss value: