#Task 1 :Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library).

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
inputs = np.array([[73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43],
                    [91, 88, 64],
                    [87, 134, 58],
                    [102, 43, 37],
                    [69, 96, 70],
                    [73, 67, 43], 
                    [91, 88, 64], 
                    [87, 134, 58], 
                    [102, 43, 37], 
                    [69, 96, 70]], dtype='float32')
print(inputs.shape)

(15, 3)


In [3]:
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],
[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.4, random_state=144)

In [5]:
reg = LinearRegression().fit(x_train,y_train)
print(reg)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [6]:
print(reg.intercept_)
print(reg.coef_)

[-2.1138153 -2.184929 ]
[[-0.37458393  0.84742796  0.69048226]
 [-0.28606915  0.7940302   0.9255152 ]]


In [7]:
y_pred = reg.predict(x_test)
print(y_pred,"\n")
print(y_test)

[[101.72674  119.089264]
 [ 57.009968  69.9292  ]
 [ 82.56357  100.8904  ]
 [101.72674  119.089264]
 [ 82.56357  100.8904  ]
 [ 57.009968  69.9292  ]] 

[[103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [103. 119.]
 [ 81. 101.]
 [ 56.  70.]]


In [8]:
from sklearn import metrics
print('\n Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))


 Mean Squared Error: 0.8518281
